/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.Matrizdb;
import DAO.mysql.generatedclasses.tables.records.ClienteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cliente extends TableImpl<ClienteRecord> {

	private static final long serialVersionUID = -715457758;

	/**
	 * The reference instance of <code>matrizdb.cliente</code>
	 */
	public static final Cliente CLIENTE = new Cliente();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ClienteRecord> getRecordType() {
		return ClienteRecord.class;
	}

	/**
	 * The column <code>matrizdb.cliente.idCliente</code>.
	 */
	public final TableField<ClienteRecord, Integer> IDCLIENTE = createField("idCliente", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.cliente.nome</code>.
	 */
	public final TableField<ClienteRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>matrizdb.cliente.cpf</code>.
	 */
	public final TableField<ClienteRecord, String> CPF = createField("cpf", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>matrizdb.cliente.saldo</code>.
	 */
	public final TableField<ClienteRecord, Double> SALDO = createField("saldo", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.cliente.apagado</code>.
	 */
	public final TableField<ClienteRecord, Byte> APAGADO = createField("apagado", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>matrizdb.cliente</code> table reference
	 */
	public Cliente() {
		this("cliente", null);
	}

	/**
	 * Create an aliased <code>matrizdb.cliente</code> table reference
	 */
	public Cliente(String alias) {
		this(alias, CLIENTE);
	}

	private Cliente(String alias, Table<ClienteRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cliente(String alias, Table<ClienteRecord> aliased, Field<?>[] parameters) {
		super(alias, Matrizdb.MATRIZDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ClienteRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CLIENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ClienteRecord> getPrimaryKey() {
		return Keys.KEY_CLIENTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ClienteRecord>> getKeys() {
		return Arrays.<UniqueKey<ClienteRecord>>asList(Keys.KEY_CLIENTE_PRIMARY, Keys.KEY_CLIENTE_CPF_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cliente as(String alias) {
		return new Cliente(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cliente rename(String name) {
		return new Cliente(name, null);
	}
}
