/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.Matrizdb;
import DAO.mysql.generatedclasses.tables.records.FilialRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Filial extends TableImpl<FilialRecord> {

	private static final long serialVersionUID = 1221701761;

	/**
	 * The reference instance of <code>matrizdb.filial</code>
	 */
	public static final Filial FILIAL = new Filial();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilialRecord> getRecordType() {
		return FilialRecord.class;
	}

	/**
	 * The column <code>matrizdb.filial.idFilial</code>.
	 */
	public final TableField<FilialRecord, Integer> IDFILIAL = createField("idFilial", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.filial.nome</code>.
	 */
	public final TableField<FilialRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>matrizdb.filial</code> table reference
	 */
	public Filial() {
		this("filial", null);
	}

	/**
	 * Create an aliased <code>matrizdb.filial</code> table reference
	 */
	public Filial(String alias) {
		this(alias, FILIAL);
	}

	private Filial(String alias, Table<FilialRecord> aliased) {
		this(alias, aliased, null);
	}

	private Filial(String alias, Table<FilialRecord> aliased, Field<?>[] parameters) {
		super(alias, Matrizdb.MATRIZDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<FilialRecord, Integer> getIdentity() {
		return Keys.IDENTITY_FILIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FilialRecord> getPrimaryKey() {
		return Keys.KEY_FILIAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FilialRecord>> getKeys() {
		return Arrays.<UniqueKey<FilialRecord>>asList(Keys.KEY_FILIAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Filial as(String alias) {
		return new Filial(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Filial rename(String name) {
		return new Filial(name, null);
	}
}
