/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.Matrizdb;
import DAO.mysql.generatedclasses.tables.records.FilialProdutoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilialProduto extends TableImpl<FilialProdutoRecord> {

	private static final long serialVersionUID = -895974620;

	/**
	 * The reference instance of <code>matrizdb.filial_produto</code>
	 */
	public static final FilialProduto FILIAL_PRODUTO = new FilialProduto();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilialProdutoRecord> getRecordType() {
		return FilialProdutoRecord.class;
	}

	/**
	 * The column <code>matrizdb.filial_produto.idFilial</code>.
	 */
	public final TableField<FilialProdutoRecord, Integer> IDFILIAL = createField("idFilial", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.filial_produto.idProduto</code>.
	 */
	public final TableField<FilialProdutoRecord, Integer> IDPRODUTO = createField("idProduto", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>matrizdb.filial_produto</code> table reference
	 */
	public FilialProduto() {
		this("filial_produto", null);
	}

	/**
	 * Create an aliased <code>matrizdb.filial_produto</code> table reference
	 */
	public FilialProduto(String alias) {
		this(alias, FILIAL_PRODUTO);
	}

	private FilialProduto(String alias, Table<FilialProdutoRecord> aliased) {
		this(alias, aliased, null);
	}

	private FilialProduto(String alias, Table<FilialProdutoRecord> aliased, Field<?>[] parameters) {
		super(alias, Matrizdb.MATRIZDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FilialProdutoRecord> getPrimaryKey() {
		return Keys.KEY_FILIAL_PRODUTO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FilialProdutoRecord>> getKeys() {
		return Arrays.<UniqueKey<FilialProdutoRecord>>asList(Keys.KEY_FILIAL_PRODUTO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FilialProdutoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FilialProdutoRecord, ?>>asList(Keys.FK_FILIAL_HAS_PRODUTO_FILIAL1, Keys.FK_FILIAL_HAS_PRODUTO_PRODUTO1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialProduto as(String alias) {
		return new FilialProduto(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FilialProduto rename(String name) {
		return new FilialProduto(name, null);
	}
}
