/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.Matrizdb;
import DAO.mysql.generatedclasses.tables.records.VendaRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Venda extends TableImpl<VendaRecord> {

	private static final long serialVersionUID = 555067249;

	/**
	 * The reference instance of <code>matrizdb.venda</code>
	 */
	public static final Venda VENDA = new Venda();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VendaRecord> getRecordType() {
		return VendaRecord.class;
	}

	/**
	 * The column <code>matrizdb.venda.idVenda</code>.
	 */
	public final TableField<VendaRecord, Integer> IDVENDA = createField("idVenda", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.idCiente</code>.
	 */
	public final TableField<VendaRecord, Integer> IDCIENTE = createField("idCiente", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.totalBruto</code>.
	 */
	public final TableField<VendaRecord, Double> TOTALBRUTO = createField("totalBruto", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.totalLiquido</code>.
	 */
	public final TableField<VendaRecord, Double> TOTALLIQUIDO = createField("totalLiquido", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.troco</code>.
	 */
	public final TableField<VendaRecord, Double> TROCO = createField("troco", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.valorPago</code>.
	 */
	public final TableField<VendaRecord, Double> VALORPAGO = createField("valorPago", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.data</code>.
	 */
	public final TableField<VendaRecord, Date> DATA = createField("data", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>matrizdb.venda.status</code>. Se 1, confirmada.
Se 0, cancelada.
	 */
	public final TableField<VendaRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "Se 1, confirmada.\nSe 0, cancelada.");

	/**
	 * Create a <code>matrizdb.venda</code> table reference
	 */
	public Venda() {
		this("venda", null);
	}

	/**
	 * Create an aliased <code>matrizdb.venda</code> table reference
	 */
	public Venda(String alias) {
		this(alias, VENDA);
	}

	private Venda(String alias, Table<VendaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Venda(String alias, Table<VendaRecord> aliased, Field<?>[] parameters) {
		super(alias, Matrizdb.MATRIZDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<VendaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_VENDA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<VendaRecord> getPrimaryKey() {
		return Keys.KEY_VENDA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<VendaRecord>> getKeys() {
		return Arrays.<UniqueKey<VendaRecord>>asList(Keys.KEY_VENDA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<VendaRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<VendaRecord, ?>>asList(Keys.FK_VENDA_CLIENTE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Venda as(String alias) {
		return new Venda(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Venda rename(String name) {
		return new Venda(name, null);
	}
}
