/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Cliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record5<Integer, String, String, Double, Byte> {

	private static final long serialVersionUID = -792463807;

	/**
	 * Setter for <code>matrizdb.cliente.idCliente</code>.
	 */
	public void setIdcliente(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matrizdb.cliente.idCliente</code>.
	 */
	public Integer getIdcliente() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matrizdb.cliente.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matrizdb.cliente.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>matrizdb.cliente.cpf</code>.
	 */
	public void setCpf(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matrizdb.cliente.cpf</code>.
	 */
	public String getCpf() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>matrizdb.cliente.saldo</code>.
	 */
	public void setSaldo(Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matrizdb.cliente.saldo</code>.
	 */
	public Double getSaldo() {
		return (Double) getValue(3);
	}

	/**
	 * Setter for <code>matrizdb.cliente.apagado</code>.
	 */
	public void setApagado(Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matrizdb.cliente.apagado</code>.
	 */
	public Byte getApagado() {
		return (Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Double, Byte> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Double, Byte> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Cliente.CLIENTE.IDCLIENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Cliente.CLIENTE.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Cliente.CLIENTE.CPF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field4() {
		return Cliente.CLIENTE.SALDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field5() {
		return Cliente.CLIENTE.APAGADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdcliente();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getCpf();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value4() {
		return getSaldo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value5() {
		return getApagado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord value1(Integer value) {
		setIdcliente(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord value3(String value) {
		setCpf(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord value4(Double value) {
		setSaldo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord value5(Byte value) {
		setApagado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClienteRecord values(Integer value1, String value2, String value3, Double value4, Byte value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClienteRecord
	 */
	public ClienteRecord() {
		super(Cliente.CLIENTE);
	}

	/**
	 * Create a detached, initialised ClienteRecord
	 */
	public ClienteRecord(Integer idcliente, String nome, String cpf, Double saldo, Byte apagado) {
		super(Cliente.CLIENTE);

		setValue(0, idcliente);
		setValue(1, nome);
		setValue(2, cpf);
		setValue(3, saldo);
		setValue(4, apagado);
	}
}
