/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Filial;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilialRecord extends UpdatableRecordImpl<FilialRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 877004553;

	/**
	 * Setter for <code>matrizdb.filial.idFilial</code>.
	 */
	public void setIdfilial(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matrizdb.filial.idFilial</code>.
	 */
	public Integer getIdfilial() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matrizdb.filial.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matrizdb.filial.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Filial.FILIAL.IDFILIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Filial.FILIAL.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdfilial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialRecord value1(Integer value) {
		setIdfilial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FilialRecord
	 */
	public FilialRecord() {
		super(Filial.FILIAL);
	}

	/**
	 * Create a detached, initialised FilialRecord
	 */
	public FilialRecord(Integer idfilial, String nome) {
		super(Filial.FILIAL);

		setValue(0, idfilial);
		setValue(1, nome);
	}
}
