/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Venda;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaRecord extends UpdatableRecordImpl<VendaRecord> implements Record8<Integer, Integer, Double, Double, Double, Double, Date, Byte> {

	private static final long serialVersionUID = 911349668;

	/**
	 * Setter for <code>matrizdb.venda.idVenda</code>.
	 */
	public void setIdvenda(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.idVenda</code>.
	 */
	public Integer getIdvenda() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matrizdb.venda.idCiente</code>.
	 */
	public void setIdciente(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.idCiente</code>.
	 */
	public Integer getIdciente() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matrizdb.venda.totalBruto</code>.
	 */
	public void setTotalbruto(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.totalBruto</code>.
	 */
	public Double getTotalbruto() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>matrizdb.venda.totalLiquido</code>.
	 */
	public void setTotalliquido(Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.totalLiquido</code>.
	 */
	public Double getTotalliquido() {
		return (Double) getValue(3);
	}

	/**
	 * Setter for <code>matrizdb.venda.troco</code>.
	 */
	public void setTroco(Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.troco</code>.
	 */
	public Double getTroco() {
		return (Double) getValue(4);
	}

	/**
	 * Setter for <code>matrizdb.venda.valorPago</code>.
	 */
	public void setValorpago(Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.valorPago</code>.
	 */
	public Double getValorpago() {
		return (Double) getValue(5);
	}

	/**
	 * Setter for <code>matrizdb.venda.data</code>.
	 */
	public void setData(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.data</code>.
	 */
	public Date getData() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>matrizdb.venda.status</code>. Se 1, confirmada.
Se 0, cancelada.
	 */
	public void setStatus(Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>matrizdb.venda.status</code>. Se 1, confirmada.
Se 0, cancelada.
	 */
	public Byte getStatus() {
		return (Byte) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Double, Double, Double, Double, Date, Byte> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Double, Double, Double, Double, Date, Byte> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Venda.VENDA.IDVENDA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Venda.VENDA.IDCIENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Venda.VENDA.TOTALBRUTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field4() {
		return Venda.VENDA.TOTALLIQUIDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field5() {
		return Venda.VENDA.TROCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field6() {
		return Venda.VENDA.VALORPAGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return Venda.VENDA.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field8() {
		return Venda.VENDA.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdvenda();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdciente();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getTotalbruto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value4() {
		return getTotalliquido();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value5() {
		return getTroco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value6() {
		return getValorpago();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value1(Integer value) {
		setIdvenda(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value2(Integer value) {
		setIdciente(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value3(Double value) {
		setTotalbruto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value4(Double value) {
		setTotalliquido(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value5(Double value) {
		setTroco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value6(Double value) {
		setValorpago(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value7(Date value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord value8(Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendaRecord values(Integer value1, Integer value2, Double value3, Double value4, Double value5, Double value6, Date value7, Byte value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VendaRecord
	 */
	public VendaRecord() {
		super(Venda.VENDA);
	}

	/**
	 * Create a detached, initialised VendaRecord
	 */
	public VendaRecord(Integer idvenda, Integer idciente, Double totalbruto, Double totalliquido, Double troco, Double valorpago, Date data, Byte status) {
		super(Venda.VENDA);

		setValue(0, idvenda);
		setValue(1, idciente);
		setValue(2, totalbruto);
		setValue(3, totalliquido);
		setValue(4, troco);
		setValue(5, valorpago);
		setValue(6, data);
		setValue(7, status);
	}
}
