/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses;


import DAO.mysql.generatedclasses.tables.Cliente;
import DAO.mysql.generatedclasses.tables.Filial;
import DAO.mysql.generatedclasses.tables.FilialProduto;
import DAO.mysql.generatedclasses.tables.Itemvenda;
import DAO.mysql.generatedclasses.tables.Produto;
import DAO.mysql.generatedclasses.tables.Venda;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in matrizdb
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table matrizdb.cliente
	 */
	public static final Cliente CLIENTE = DAO.mysql.generatedclasses.tables.Cliente.CLIENTE;

	/**
	 * The table matrizdb.filial
	 */
	public static final Filial FILIAL = DAO.mysql.generatedclasses.tables.Filial.FILIAL;

	/**
	 * The table matrizdb.filial_produto
	 */
	public static final FilialProduto FILIAL_PRODUTO = DAO.mysql.generatedclasses.tables.FilialProduto.FILIAL_PRODUTO;

	/**
	 * The table matrizdb.itemvenda
	 */
	public static final Itemvenda ITEMVENDA = DAO.mysql.generatedclasses.tables.Itemvenda.ITEMVENDA;

	/**
	 * The table matrizdb.produto
	 */
	public static final Produto PRODUTO = DAO.mysql.generatedclasses.tables.Produto.PRODUTO;

	/**
	 * The table matrizdb.venda
	 */
	public static final Venda VENDA = DAO.mysql.generatedclasses.tables.Venda.VENDA;
}
