/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses;


import DAO.mysql.generatedclasses.tables.Cliente;
import DAO.mysql.generatedclasses.tables.Filial;
import DAO.mysql.generatedclasses.tables.FilialProduto;
import DAO.mysql.generatedclasses.tables.Itemvenda;
import DAO.mysql.generatedclasses.tables.Produto;
import DAO.mysql.generatedclasses.tables.Venda;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matrizdb extends SchemaImpl {

	private static final long serialVersionUID = 1885166833;

	/**
	 * The reference instance of <code>matrizdb</code>
	 */
	public static final Matrizdb MATRIZDB = new Matrizdb();

	/**
	 * No further instances allowed
	 */
	private Matrizdb() {
		super("matrizdb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Cliente.CLIENTE,
			Filial.FILIAL,
			FilialProduto.FILIAL_PRODUTO,
			Itemvenda.ITEMVENDA,
			Produto.PRODUTO,
			Venda.VENDA);
	}
}
