/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.FilialProduto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilialProdutoRecord extends UpdatableRecordImpl<FilialProdutoRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 189479686;

	/**
	 * Setter for <code>matrizdb.filial_produto.idFilial</code>.
	 */
	public void setIdfilial(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matrizdb.filial_produto.idFilial</code>.
	 */
	public Integer getIdfilial() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matrizdb.filial_produto.idProduto</code>.
	 */
	public void setIdproduto(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matrizdb.filial_produto.idProduto</code>.
	 */
	public Integer getIdproduto() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return FilialProduto.FILIAL_PRODUTO.IDFILIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return FilialProduto.FILIAL_PRODUTO.IDPRODUTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdfilial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdproduto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialProdutoRecord value1(Integer value) {
		setIdfilial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialProdutoRecord value2(Integer value) {
		setIdproduto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilialProdutoRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FilialProdutoRecord
	 */
	public FilialProdutoRecord() {
		super(FilialProduto.FILIAL_PRODUTO);
	}

	/**
	 * Create a detached, initialised FilialProdutoRecord
	 */
	public FilialProdutoRecord(Integer idfilial, Integer idproduto) {
		super(FilialProduto.FILIAL_PRODUTO);

		setValue(0, idfilial);
		setValue(1, idproduto);
	}
}
