/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Produto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProdutoRecord extends UpdatableRecordImpl<ProdutoRecord> implements Record4<Integer, String, Double, Byte> {

	private static final long serialVersionUID = -305273446;

	/**
	 * Setter for <code>matrizdb.produto.idProduto</code>.
	 */
	public void setIdproduto(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matrizdb.produto.idProduto</code>.
	 */
	public Integer getIdproduto() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matrizdb.produto.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matrizdb.produto.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>matrizdb.produto.valor</code>.
	 */
	public void setValor(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matrizdb.produto.valor</code>.
	 */
	public Double getValor() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>matrizdb.produto.apagado</code>.
	 */
	public void setApagado(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matrizdb.produto.apagado</code>.
	 */
	public Byte getApagado() {
		return (Byte) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Double, Byte> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Double, Byte> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Produto.PRODUTO.IDPRODUTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Produto.PRODUTO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Produto.PRODUTO.VALOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return Produto.PRODUTO.APAGADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdproduto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getValor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getApagado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProdutoRecord value1(Integer value) {
		setIdproduto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProdutoRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProdutoRecord value3(Double value) {
		setValor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProdutoRecord value4(Byte value) {
		setApagado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProdutoRecord values(Integer value1, String value2, Double value3, Byte value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProdutoRecord
	 */
	public ProdutoRecord() {
		super(Produto.PRODUTO);
	}

	/**
	 * Create a detached, initialised ProdutoRecord
	 */
	public ProdutoRecord(Integer idproduto, String nome, Double valor, Byte apagado) {
		super(Produto.PRODUTO);

		setValue(0, idproduto);
		setValue(1, nome);
		setValue(2, valor);
		setValue(3, apagado);
	}
}
